name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            CICD_IP_ADD: ${{ secrets.CICD_IP_ADD }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add EC2 host to known hosts
              run: ssh-keyscan -H $CICD_IP_ADD >> ~/.ssh/known_hosts

            - name: Deploy to EC2

              run: |
                  # Replace the following with your deployment script or commands
                  ssh ubuntu@$CICD_IP_ADD << EOF
                  cd /home/ubuntu/veris_ins
                  chmod +x deploy.sh
                  ./deploy.sh
                  EOF
